### ISSUE TITLE
No Examples

### ISSUE THREAD

**Issue by SoundsSerious** [Grandbrain/Kalman#2]
Hey!

Great library and documentation you have here, while kalman concepts are semi-universal an experienced person can put some code together with your library in a short time. Many people have difficulty just understanding theses concepts, and perhaps a simple 3d motion example of how this could be used would increase code usage.

Just a thought! Keep at it brain ;)

**Comment by Lewishw** [comment]
If anyone is looking for an example, there is one available over there : [http://kalman.sourceforge.net/doc.php](url)
The architecture is a bit different, but overall, the code seems to be a copy of what is available on sourceforge.

**Comment by lomakinandrei** [comment]
At this point, I've added just one example of using the filter. I updated the repository and added an example and a manual to it. I will be glad to your participation in the creation of new examples.
